project:
  type: website
  output-dir: docs

website:
  title: "Kate Bierwagen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: adventures.qmd
        text: Adventures

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



