project:
  type: website
  output-dir: docs

website:
  title: "Kate Bierwagen"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects/index.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - href: adventures.qmd
        text: Travels
format:
  html:
    theme: 
      - cosmo
      - styles.scss
    mainfont: Playfair Display
    code-fold: true






